### ISSUE TITLE
Using with custom foreach

### ISSUE THREAD

**Issue by mattklinker** [bramstein/knockout.selection#92]
First off, thanks for providing this, it appears to be more complicated to setup then I had even feared!  Your library appears to work quite well, and I had no issue with it until I replaced my use of the normal 'foreach' binding with a custom implementation 'virtualForeach' where I just want to limit the number of items rendered on init and lazy load new items as required.

My virtualForeach works as I expect, but I've broken the features provided by knockout.selection.  I can switch my markup between the 2 bindings and 'foreach' always works and virtual never does.  Is there anything in particular that needs to be maintained and/or setup in order for knockout.selection to continue working?  I can provide a copy of the binding if you'd like, and I'll work on a fiddle but was having troubles getting all the sources in since I can't pull from github.

**Comment by mattklinker** [comment]
Turns out I was going down the wrong path entirely, my problem was actually caused by some other issues and the fact that my style bindings were on the container/template node for my virtual container and so did not actually get bound the same was as the child objects I was seeing.  

Anyway, thanks again for the great library.

**Comment by sunesimonsen** [comment]
I happy that you solved your problem, sorry for not getting around to help you.
